directories:
  clean_data_dir: "data/DistanceEstimationData"
  raw_calibration_data_dir: "data"
  raw_trap_data_dir: "../Images/Distance_Estimation/Red_Deer"
  possible_sources:
    - "Distanzfotos_II"
    - "Distanzfotos II"
    - "Distanzfotos"

gpu:
  used_gpu_idx: "0"
  cuda_idx: "cuda:0"

mask_generation:
  batch_size: 2
  num_workers: 2
  segmenter_pretrained_in: 'ade'
  lightweight_segmenter: False
  resize_first: True
  debug_mode: False
  min_mask_pixel_image: 3000
  min_mask_pixel_area: 1000


